version: "3.8"
services:
  nacos-register-service:
    image: docker.io/nacos/nacos-server:v2.2.0
    container_name: nacos-register-service
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=nacos-mysql
      - MYSQL_SERVICE_DB_NAME=nacos-config
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      mysql:
        condition: service_healthy
  nacos-mysql:
    image: docker.io/arm64v8/mysql:8.0
    container_name: nacos-mysql
    hostname: nacos-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nacos-config
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=nacos
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
  hello-service-baseline:
    image: docker.io/redxiiikk/learn-hello-service:1.0.0
    container_name: hello-service-baseline
    build:
      context: ../hello-service
    environment:
      - APPLICATION_SERVER_PORT=8080
      - NACOS_SERVER_ADDR=nacos-register-service:8848
      - NACOS_NAMESPACE=dev-cluster
      - NACOS_GROUP=baseline
  hello-service-dev:
    image: docker.io/redxiiikk/learn-hello-service:1.0.0
    container_name: hello-service-dev
    environment:
      - APPLICATION_SERVER_PORT=8081
      - NACOS_SERVER_ADDR=nacos-register-service:8848
      - NACOS_NAMESPACE=dev-cluster
      - NACOS_GROUP=dev-redxiiikk