server:
  port: ${APPLICATION_SERVER_PORT:8080}
spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.client.discovery.composite.reactive.ReactiveCompositeDiscoveryClientAutoConfiguration
      - org.springframework.cloud.client.discovery.simple.reactive.SimpleReactiveDiscoveryClientAutoConfiguration
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: hello-service
          uri: lb://hello-service
          predicates:
            - Path=/hello-service/**
          filters:
            - AddRequestHeader=X-SC-LB-Hint, baseline
    nacos:
      discovery:
        enabled: true
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway