# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
    monitor: 'codelab-monitor'
rule_files:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]
  - job_name: 'kafka'
    static_configs:
      - targets: [ 'kafka:1234' ]
  - job_name: 'kafka-lag-exporter'
    static_configs:
      - targets: [ 'kafka-lag-exporter:9999' ]
  - job_name: 'flink'
    static_configs:
      - targets: [ 'jobmanager:9249' ]

