version: "3"
services:
  jobmanager:
    container_name: job-manager
    image: docker.io/flink:1.14.3-scala_2.12-java11
    command:
      - jobmanager
    ports:
      - "8081:8081"
      - "5006:5006"
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        env.java.opts.jobmanager: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5006"
  taskmanager:
    depends_on:
      - jobmanager
    container_name: taskmanager
    image: docker.io/flink:1.14.3-scala_2.12-java11
    command:
      - taskmanager
    ports:
      - "5005:5005"
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        env.java.opts.taskmanager: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
  redis:
    container_name: redis
    image: docker.io/redis:6.2.6
    ports:
      - "6379:6379"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.0.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  kowl:
    image: quay.io/cloudhut/kowl:v1.4.0
    restart: on-failure
    container_name: kowl
    hostname: kowl
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: kafka:19092
    depends_on:
      - kafka
